import type { Metadata } from 'next';

import './globals.css';
import Header from '@/components/Header';
import Script from 'next/script';
import { Toaster } from 'react-hot-toast';
import Footer from '@/components/Footer';

export const metadata: Metadata = {
    title: 'Active Tribe',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className="font-gilroy max-w-[1920px]">
                {/* <Script
                    src="https://www.google.com/recaptcha/api.js"
                    async
                    defer
                ></Script> */}
                <Script
                    strategy="beforeInteractive"
                    src={`https://www.google.com/recaptcha/api.js?render=${process.env.NEXT_PUBLIC_RECAPTCHA_SITE_KEY}&hl=en`}
                />
                <Toaster />
                <Header />
                {children}
                <Footer />
            </body>
        </html>
    );
}
